### ISSUE TITLE
conda-forge depenencies

### ISSUE THREAD

**Issue by Tara-Lakshmipathy** [pyiron/pyironFlow#24]
I just tried to install using the command `conda install -c conda-forge pyironflow`.

The following required packages did not get installed:
- esbuild
- nodejs

**Comment by Tara-Lakshmipathy** [comment]
Also just FYI, I need to use pyironflow by `from pyironflow.pyironflow import PyironFlow`
Is the second `pyironflow` needed? Should we rename the file or something?

**Comment by jan-janssen** [comment]
They should only be required for recompiling `pyironflow` but they should be required for using `pyironflow` as far as I understand.

**Comment by Tara-Lakshmipathy** [comment]
Should be required for using ``
