### ISSUE TITLE
Update conda install

### ISSUE THREAD

**Issue by Tara-Lakshmipathy** [pyiron/pyironFlow#28]
Currently installing with `conda install -c conda-forge pyironflow` throws the error: No module named 'pyironflow.themes'

The conda forge installation needs to be updated with the new files which are present in the repo in the main branch.
@jan-janssen and @srmnitc  could you help me with this and teach me a bit about conda in the process?

**Comment by jan-janssen** [comment]
![pyironrelease](https://github.com/user-attachments/assets/8b5f0e5a-ae70-4a47-931e-60d483366a55)

**Comment by jan-janssen** [comment]
The new version is in a few minutes available on pypi https://pypi.org/project/pyironflow/ and approximately 24-hours later on conda-forge https://anaconda.org/conda-forge/pyironflow .

**Comment by Tara-Lakshmipathy** [comment]
Thanks!
