### ISSUE TITLE
Pictures in the readme are not visible for outside users

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/pyironFlow#33]
If I use a private browsing window, the images in the readme are not loaded correctly. Here is a screenshot to demonstrate this:
<img width="1297" alt="Screenshot 2024-12-10 at 10 36 15 AM" src="https://github.com/user-attachments/assets/86cff98c-28fb-4cd7-bf98-ef0526e30f96">

**Comment by Tara-Lakshmipathy** [comment]
Thanks for pointing it out, should work now. Also added conda installation instructions.
