### ISSUE TITLE
merging with dev_tara

### ISSUE THREAD

**Issue by JNmpi** [pyiron/pyironFlow#6]
Thanks, @Tara-Lakshmipathy for the changes and enhancements regarding node color and edge width. They make the visual appearance of our visual programming gui very nice, and I have merged them into the main branch. A few suggestions/ideas:

- Could you please make a pull request for your pyiron_workflow dev_tara branch? It would be good to have the gui_color extension in the main branch, so that the main branch of gui and pyiron_workflow are compatible.
- It looks like the border width is introduced as a magic parameter in the widget.js file. It would be nice to be able to set it from the Python side when calling the widget.
- I also merged your dev_tara branch in pyiron_nodes into my development branch. Since I did not install the fenics ufl packages, I could not test your nodes.

**Comment by Tara-Lakshmipathy** [comment]
Hi @JNmpi, I have created a pull request in `pyiron_workflow` for updating gui colors. But I don't think a pull request was created here in xyflow to merge into the main branch. Created one now.

**Comment by Tara-Lakshmipathy** [comment]
Hi @JNmpi, I have created a pull request in pyiron_workflow for updating gui colors.

**Comment by JNmpi** [comment]
Thanks, @Tara-Lakshmipathy
